spring:
  application:
    name: expense-tracker-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8086
  servlet:
    context-path: /api

logging:
  level:
    com.expensetracker: DEBUG
    org.springframework.security: DEBUG

