spring:
  application:
    name: expense-tracker-backend
  
  datasource:
    url: jdbc:h2:mem:expense_tracker
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8086
  servlet:
    context-path: /api

logging:
  level:
    com.expensetracker: DEBUG
    org.springframework.security: DEBUG

